### PR TITLE
Add operadriver to path and add OS X and Linux testing

### PR DESCRIPTION
**Pull request by gauntface**
This just brings operadriver to be a bit closer to current node-chromedriver.

In an ideal world, both these driver packages would be under one repo and share code where possible ;)

---
This change is [Reviewable](https://reviewable.io/reviews/cnpm/node-operadriver/2)

### CODE REVIEW

**Comment by gauntface** [comment]
All tests pass apart from one on Travis but I don't have the rights to re-run the test.

**Comment by fengmk2** [comment]
+1

**Comment by fengmk2** [comment]
Yep, maybe we can merge both into one repo.

**Comment by fengmk2** [comment]
Landed 8fca3ad1ff16f742ce99925d0cd95000b034ff6b

**Comment by fengmk2** [comment]
Release 1.0.0

**Pull request closed without merging**
